### ISSUE TITLE
Help FF13LR

### ISSUE THREAD

**Issue by wandersonareis** [lehieugch68/FFXIII-XGR-Unpacker#1]
Hello!
Did you translate FFXIII using the Pulse tool?
I translated FFXIII and FFXIII-2 using the Pulse..

FF13LR I have a problem with the compression of the ZTR file.
The auto_yus.ztr file needs compression to reduce the size, and the auto_yus.bin does not crash.

Do you have time to take a look at this file and the ztr compression?

If you use Pulse's FakeCompress on auto_yus.ztr the game won't crash, but it calculates pointers to the wrong text offset.
One solution would be to fix the pointers to the compressed files and the best would be to work on a better compression, but this is too much work for just one file.

**Comment by lehieugch68** [comment]
I translated FFXIII-1 with Pulse, this is a tool I wrote to extract the font files of FFXIII-3 for a friend, I think there are text extraction tools already, so I haven't really looked into them yet. .

I'm focusing on writing the extraction tool for Fatal Frame first, but you can send a sample file for me to take a look at it. Anyway, I'm not good at compression algorithms, so I can't say anything in advance.

**Comment by wandersonareis** [comment]
[auto_yus_us_compressed.zip](https://github.com/lehieugch68/FFXIII-XGR-Unpacker/files/7645210/auto_yus_us_compressed.zip)
This is the original file. This WPD is a container with 2 files.
The header contains:
magic number
number of files in the container
file name always followed by file offset, file size and file extension.

[00000001_auto_yus_us_PulseZtrCompressed.zip](https://github.com/lehieugch68/FFXIII-XGR-Unpacker/files/7645265/00000001_auto_yus_us_PulseCompressed.zip)
It is the ZTR file that is the problem.
Pulse can compress ANSI used in text keys, but it cannot compress the text.
There is a bug that does not calculate the correct pointers to the text.

The game crashes on this file because the text is not compressed. The WPD file size exceeds 256kb causing the crash during the loading of Yusna's city.
           
I made a version to extract the WPD container and handle ZTR.
[MyVersion](https://github.com/rhadamants/Pulse)
[PulseAlbeoris](https://github.com/Albeoris/Pulse)

Albeoris warning bug file : Don't use it for text packing or fix BlockOffset first!
        // It should be contains offset if the begining of the entry was mixed with a previous tail.
[ZtrFileEncoding](https://github.com/Albeoris/Pulse/blob/master/Pulse.FS/ZTR/ZtrFileEncoding.cs)
[BlockOffset](https://github.com/Albeoris/Pulse/blob/master/Pulse.FS/ZTR/ZtrFileTextPacker.cs)

**Comment by lehieugch68** [comment]
Successful compression with large files (with many blocks).

![image](https://user-images.githubusercontent.com/51288927/144644951-eba78693-b1d9-4c76-be4a-81b8e4f3a7a7.png)

The compressed file has been reduced to 65kb compared to uncompressed (fake compression) using only 3 key-value pairs (I call it level 0 compression), and more key-value pairs could be used to achieve better compression. I'm developing a program to do this automatically.

![image](https://user-images.githubusercontent.com/51288927/144645443-b5ac48a1-1400-462a-9095-6fb9b398b47c.png)

**Comment by wandersonareis** [comment]
That's great!
You intend to make a tool just to compress the Pulse encoded ztr or just compatible with the strings file?

**Comment by lehieugch68** [comment]
You can use Pulse's ZTR fake compression file, decompress and compress it again.

**Comment by wandersonareis** [comment]
The tool is not yet complete. I couldn't test the compression.
I am waiting for more news.

Like non-ASCII  text and testing the compression.

Thanks for your time!

**Comment by lehieugch68** [comment]
Remember that the game only accepts ASCII characters, you must replace all UTF8 characters to some ASCII characters before compressing.

**Comment by wandersonareis** [comment]
Is it possible to do it only for compression?
Pulse encodes the ZTR file without compression and your tool compresses it.
If I use ASCII in the texts I will lose the non-ASCII characters.

Albeoris tells me that the keys for the texts are in ASCII, but the text itself is not.
The texts use 0x85, 0x?? encoding for non-ASCII characters.

By translating I can display the texts with accents.

The game has a font with Latin characters.

[Encoding Tags](https://github.com/rhadamants/Pulse/blob/master/Pulse.Core/Encoding/Tags/FFXIIITextTag.cs)

[Keys get ASCII](https://github.com/rhadamants/Pulse/blob/master/Pulse.FS/ZTR/ZtrFileKeysPacker.cs)
And text get Pulse encoding
[Text get Pulse encoding](https://github.com/rhadamants/Pulse/blob/master/Pulse.Core/Encoding/FFXIIITextEncoding.cs)

The game accepts Little Endian. Dialogs use little endian. The "resident\system" uses big endian because of a bug that you could not sort the items in the character's inventory. If you use little endian, this does not cause a problem in the game.
[Ztr packer](https://github.com/rhadamants/Pulse/blob/master/Pulse.FS/ZTR/ZtrFilePacker.cs)

**Comment by wandersonareis** [comment]
[auto_yus_gr_jp_sp.zip](https://github.com/lehieugch68/FFXIII-XGR-Unpacker/files/7654614/auto_yus_gr_jp_sp.zip)
Texts in Spanish, German and Japanese
Only the keys for the texts are ASCII.
ASCII is useless for the Japanese language

**Comment by lehieugch68** [comment]
Is the file you sent me already compressed?

![image](https://user-images.githubusercontent.com/51288927/144742193-e5260876-7186-4030-a8b3-a569ae89884d.png)

**Comment by wandersonareis** [comment]
Original game files. No Pulse modification.

**Comment by wandersonareis** [comment]
In test.
auto_yus_us wpd + ztr = 264kb
Game crash.

**Comment by wandersonareis** [comment]
[auto_yus_GermanItalian,SpanishOriginalNoPulse.zip](https://github.com/lehieugch68/FFXIII-XGR-Unpacker/files/7655976/auto_yus_OriginalNoPulse.zip)
[auto_yus_usEnglishOriginalNoPulse.zip](https://github.com/lehieugch68/FFXIII-XGR-Unpacker/files/7655977/auto_yus_usEnglishOriginalNoPulse.zip)

My translation for auto_yus_us using CompressZtrContent on text.
[00000001_auto_yus_usPulseTextCompressZtrContent.zip](https://github.com/lehieugch68/FFXIII-XGR-Unpacker/files/7655978/00000001_auto_yus_usPulseTextCompressZtrContent.zip)

Game crash if this file size > 256kb

**Comment by lehieugch68** [comment]
Try this file. Let me know if the game crashes (if you replace it to the bin file, the total size is 254kb).
[00000001_auto_yus_us.zip](https://github.com/lehieugch68/FFXIII-XGR-Unpacker/files/7656338/00000001_auto_yus_us.zip)

**Comment by wandersonareis** [comment]
Not crash game

**Comment by wandersonareis** [comment]
But I don't know where to find these texts given from the game. 
I only know that during the loading of the city of Yusnan the game crashes or not.

**Comment by lehieugch68** [comment]
At least it worked. I will send you a new file tomorrow.

**Comment by wandersonareis** [comment]
[Image from white_img2a\txtres\event\ev_comn_020](https://imgur.com/dxr5n7p)
Start new game CG.

Compression is working perfectly in game.
